### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#692]
- [ ] Unobtrusive Javascript (#666)
- [ ] Promise-based approach (#226) (#490)
- [ ] Remove jQuery dependency
- [ ] Bring CodeClimate score to 4.0 (#593)
- [ ] Use ES6
- [ ] Remove the uniqueness middleware (#512) (#597)
- [ ] Run JavaScript tests on CI (#591)

Aumentare il punteggio su CodeClimate
Generare il file javascript tramite yarn + webpack
Abbandonare CoffeeScript in favore di ES6

**Comment by tagliala** [comment]
# 4.0, 6.0, 7.0, 8.0 OMG! 😱 

## Version 6.0
I've intentionally skipped 5.0 because I didn't want a version number which could recall Rails 5.0. As I said before, CSV will follow its own versioning system.

Version 6.0 is basically it's the "old" 4.2 CSV updated to Rails 5.

### Breaking changes 
  - Drop Rails 4 support

### New features
  - Rails 5.0 support

---

## Version 7.0
Version 7.0 drops the active record middleware. You should be able to update to this version if you didn't use remote validators before (uniqueness or custom remote validators).

You should consider to setup your own implementation of remote validators and get rid of the CSV middleware because it is not secure (data disclosure) and it is not protected

### Breaking changes 
  - Drop the active record middleware

---

## Version 8.0
It should not contain breaking changes. I've preferred to bump up the major because of potential breaking changes if you monkey patched the gem. If you didn't touch CSV internals, you should be able to use CSV >= 8.0

**Comment by fleck** [comment]
Working on setting up an Vanilla JavaScript version  https://github.com/fleck/client_side_validations/tree/ES. I'm using rollup, I see you had mentioned using webpack, but for a library rollup is better suited. JS tests are passing and there's a lot of refactoring that could still be done. There are a couple of failing tests relating to copying assets. I can commit more time to this, but wanted to get some feedback before spending more time.

**Comment by tagliala** [comment]
@fleck thanks for your work, it looks good!

Please submit a PR, I will start a review there.

PS: at the moment I'm without my development machine, so please be patient
